### ISSUE TITLE
Can't input new values in Configure Coordinates

### ISSUE THREAD

**Issue by Saturate** [megaspazz/EverWingForever#1]
I can't edit the input fields, so they are always 0.

**Comment by megaspazz** [comment]
In the README, it describes how to set the coordinates of the game.

Basically, you have to use keyboard shortcuts to set initial estimates for the coordinates (make sure these are outside but still close to the game region).  Then, click the button at the bottom to automatically detect the game region.  If you always play with the game in the same region (e.g. a maximized Chrome browser window), you will only have to set this once since the program will remember your last-used settings.

I have currently disabled user-input into those text fields because I didn't want to validate user input.  Maybe I will add this in later :)
